# workflow:
#   rules:
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#     - when: never

variables:
  TF_ROOT: open5gs/infrastructure/eks
  TF_STATE_NAME: open5gs

include:
  - template: Terraform/Base.gitlab-ci.yml  
  - template: Jobs/SAST-IaC.gitlab-ci.yml   

stages:
  - validate
  - test
  - build
  - deploy
  - cleanup 
  - install_helm
  - smoke_test 

fmt:
  extends: .terraform:fmt
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
  needs: []
  rules:
    - changes:
        paths:
          - open5gs/infrastructure/eks/*.tf

validate:
  extends: .terraform:validate
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
  needs: []
  rules:
    - changes:
        paths:
          - open5gs/infrastructure/eks/*.tf

build:
  extends: .terraform:build
  resource_group: $TF_STATE_NAME
  environment:
    name: $TF_STATE_NAME
    action: prepare
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
  # rules:
  #   - changes:
  #       paths:
  #         - open5gs/infrastructure/eks/*.tf
 
deploy: 
  extends: .terraform:deploy
  resource_group: $TF_STATE_NAME
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
    action: start
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
  # rules:
  #   - changes:
  #       paths:
  #         - open5gs/infrastructure/eks/*.tf

cleanup:
  extends: .terraform:destroy
  resource_group: $TF_STATE_NAME
  dependencies:
    - deploy
  environment:
    name: $TF_STATE_NAME
    action: stop
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
  when: manual

kics_scan:
  image: 
    name: checkmarx/kics
    entrypoint: [""]
  stage: test
  allow_failure: true
  script:
    - apk update
    - apk add ca-certificates openssl
    - apk add curl
    - curl -LO https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
    - tar -zxvf helm-v3.7.0-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/
    - helm version
    - helm repo add openverso https://gradiant.github.io/openverso-charts/ 
    - helm template open5gs openverso/open5gs --values open5gs_values.yml > open5gs.yaml 
    - kics scan -p open5gs.yaml -t Kubernetes | tee security-scan.txt
  artifacts:
    paths: 
      - security-scan.txt
      - open5gs.yaml
      
install_open5gs:
  image:
    name: alpine/helm
    entrypoint: [""]
  stage: install_helm
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  environment:
    name: open5gs_cluster 
  script:
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
    - kubectl apply -f openverso_namespace.yaml
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm upgrade --install open5gs openverso/open5gs --namespace openverso --values https://raw.githubusercontent.com/DISHDevEx/napp/main/napp/open5gs_values/5gSA_ues_values.yaml

install_ueransim:
  image:
    name: alpine/helm
    entrypoint: [""]
  stage: install_helm
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  environment:
    name: open5gs_cluster 
  script: 
    - apk add --no-cache python3 py3-pip 
    - pip3 install --upgrade pip 
    - pip3 install --no-cache-dir awscli
    - aws --version
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
    - helm repo add openverso https://gradiant.github.io/openverso-charts/
    - helm upgrade --install ueransim-gnb openverso/ueransim-gnb --namespace openverso --values https://raw.githubusercontent.com/DISHDevEx/napp/main/napp/open5gs_values/gnb_ues_values.yaml

ue_populate:
  allow_failure: true
  stage: smoke_test
  image: ubuntu:latest
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  environment: 
    name: open5gs_cluster
  script:
    - apt-get update && apt-get install -y curl unzip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
    - POPULATE_POD=$(kubectl -n openverso get pod --output=jsonpath={.items..metadata.name} -l app.kubernetes.io/component=populate)
    - kubectl -n openverso cp ./ue_populate.sh $POPULATE_POD:/tmp/ue_populate.sh
    - kubectl -n openverso exec $POPULATE_POD -- /tmp/ue_populate.sh

smoke_test:
  image: ubuntu:latest
  variables:
    REGION: us-east-1
    CLUSTER_NAME: cntf-open5gs-cluster
  needs: 
    - ue_populate
  stage: smoke_test
  environment:
    name: open5gs_cluster 
  script:
    - apt-get update && apt-get install -y curl unzip
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
    - UE_POD=$(kubectl -n openverso get pod --output=jsonpath={.items..metadata.name} -l app.kubernetes.io/component=ues)
    - kubectl -n openverso cp ./ueransim_smoke_test.sh $UE_POD:/tmp/ueransim_smoke_test.sh
    - kubectl -n openverso exec $UE_POD -- /tmp/ueransim_smoke_test.sh
 
    
