# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: gitlab-runner-secrets-role
#   namespace: gitlab-runner
# rules:
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["create"]

# ---  

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: gitlab-runner-secrets-binding
#   namespace: gitlab-runner
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: gitlab-runner
# roleRef:
#   kind: Role
#   name: gitlab-runner-secrets-role
#   apiGroup: rbac.authorization.k8s.io

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app: gitlab-runner
    chart: gitlab-runner-0.41.0
    release: "gitlab-runner"
    heritage: "Helm"
# Source: gitlab-runner/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "ClusterRole"
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app: gitlab-runner
    chart: gitlab-runner-0.41.0
    release: "gitlab-runner"
    heritage: "Helm"

rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
# Source: gitlab-runner/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: "ClusterRoleBinding"
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app: gitlab-runner
    chart: gitlab-runner-0.41.0
    release: "gitlab-runner"
    heritage: "Helm"

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: gitlab-runner
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: "gitlab-runner"


