mode: daemonset

config:
  exporters:
    coralogix:
      # The Coralogix traces ingress endpoint
      traces:
        endpoint: "ingress.coralogix.us:443"
      metrics:
        endpoint: "ingress.coralogix.us:443"
      logs:
        endpoint: "ingress.coralogix.us:443"
      # Your Coralogix private key is sensitive
      private_key: "${CORALOGIX_WRITE_KEY}"
      application_name: "open5gs"
      subsystem_name: "open5gs"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s

  extensions:
    health_check: {}
  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter:
      limit_percentage: 50
      check_interval: 1s
      spike_limit_percentage: 30
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:9090']
  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch, memory_limiter]
        exporters: [prometheus]
    extensions:
      - health_check
